# Generated by Django 3.2.6 on 2021-08-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.SmallIntegerField()),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('price_usd', models.SmallIntegerField()),
                ('price_uah', models.SmallIntegerField()),
                ('year', models.SmallIntegerField()),
                ('race', models.SmallIntegerField()),
                ('gearbox', models.CharField(max_length=256)),
                ('drivename', models.CharField(max_length=256)),
                ('vin', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
